services:
    nginx:
        restart: unless-stopped
        image: nginx:latest
        ports:
            - 5000:5000
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/conf.d:/etc/nginx/conf.d:ro
            - /var/log/nginx:/var/log/nginx
            - /etc/letsencrypt/live/osrm.home.mopalinski.com-0001/fullchain.pem:/etc/nginx/ssl/osrm.home.mopalinski.com/fullchain.pem:ro
            - /etc/letsencrypt/live/osrm.home.mopalinski.com-0001/privkey.pem:/etc/nginx/ssl/osrm.home.mopalinski.com/privkey.pem:ro
            - files:/var/www/files:ro
        depends_on:
            - osrm-backend

    osrm-backend:
        restart: unless-stopped
        image: ghcr.io/project-osrm/osrm-backend
        command: osrm-routed --algorithm mld /data/poland-latest.osrm
        volumes:
            - ./data/:/data

volumes:
    files:
